site_name: mybrainlab
site_url: https://dutoumanwulao.github.io/mybrainlab/
theme:
  name: material
  language: zh 
  features:
    - content.code.copy        # 启用中文界面


  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: 切换到暗黑模式
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: 切换到浅色模式

markdown_extensions:
  - pymdownx.highlight     # 语法高亮
  - pymdownx.inlinehilite


nav:
  - 首页: index.md
  - 指南:
      - 概览: guide/index.md
      - 操作用法: guide/usage.md

