name: Deploy MkDocs site

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. 检出代码
      - uses: actions/checkout@v3

      # 2. 安装 Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # 3. 安装依赖：mkdocs-material
      - name: Install dependencies
        run: |
          pip install mkdocs-material

      # 4. 构建站点
      - name: Build MkDocs site
        run: |
          mkdocs build --clean

      # 5. 部署到 gh-pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
          publish_branch: gh-pages
